Don't validate Python 3.6 on windows
This is apparently no longer available, per the error from the
`actions/setup-python@v1` step:

    Error: Version 3.6 with arch x64 not found
    Available versions:
    3.10.2 (x86)
    3.7.9 (x86)
    3.8.10 (x86)
    3.9.10 (x86)
    3.10.2 (x64)
    3.7.9 (x64)
    3.8.10 (x64)
    3.9.10 (x64)