Combined sqlalchemy bugfixes & changelog entry (#1534)
* Update partial.py

Two bugs:

1. `left_path` can be an empty tuple. And it will throw
```
assert left_path[0] == Variable("_this")
IndexError: tuple index out of range
```
2. In the case that `left` is an ORM object, then you also want to check `isinstance(left, constraint_type)`.

I'm probably missing subtleties, but I can confirm, that on my project, I needed the extra `or` condition, or valid resources returned by `oso.authorized_resources` were dropped.

* handle python `bool`

`and_filter` crashed due to `<python_bool> & <sqlalchemy_expression>` failing due to type-error.

* Add changelog entry RE sqlalchemy-oso bug fixes

* add username to allowed_words.txt for docs linting

Co-authored-by: Jack Reilly <72682052+jackdreillyvia@users.noreply.github.com>